# Generated by Django 3.1.5 on 2021-01-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blockchain', '0002_chain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='previous_hash',
            field=models.IntegerField(),
        ),
    ]
