# Generated by Django 3.1.5 on 2021-01-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blockchain', '0003_auto_20210116_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='previous_hash',
            field=models.TextField(),
        ),
    ]
